In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import yfinance as yf
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
from sklearn.metrics import r2_score, precision_score, mean_absolute_error
from warnings import filterwarnings
filterwarnings('ignore')

In [12]:
## STLD

In [2]:
Stock = yf.Ticker("STLD")
df = Stock.history(period = '20y')
df.head()

Open      High       Low     Close   Volume  \
Date                                                                         
2004-02-23 00:00:00-05:00  3.885004  3.969744  3.860559  3.898041  1254000   
2004-02-24 00:00:00-05:00  3.855669  3.899669  3.780707  3.852410  1534000   
2004-02-25 00:00:00-05:00  3.880115  3.927374  3.805152  3.837744  1675200   
2004-02-26 00:00:00-05:00  3.827967  3.837744  3.772560  3.810041  2266000   
2004-02-27 00:00:00-05:00  3.800263  3.956706  3.780708  3.951818  2272800   

                           Dividends  Stock Splits  
Date                                                
2004-02-23 00:00:00-05:00        0.0           0.0  
2004-02-24 00:00:00-05:00        0.0           0.0  
2004-02-25 00:00:00-05:00        0.0           0.0  
2004-02-26 00:00:00-05:00        0.0           0.0  
2004-02-27 00:00:00-05:00        0.0           0.0

In [56]:
df.drop(['Dividends', 'Stock Splits'], axis = 1, inplace = True)
df['Next Day Price'] = df['Close'].shift(-1)
df['Target'] = (df['Next Day Price'] > df['Close']).astype(int)
df.head()

Open      High       Low     Close   Volume  \
Date                                                                         
2004-02-23 00:00:00-05:00  3.885004  3.969744  3.860560  3.898041  1254000   
2004-02-24 00:00:00-05:00  3.855669  3.899669  3.780707  3.852410  1534000   
2004-02-25 00:00:00-05:00  3.880116  3.927375  3.805154  3.837746  1675200   
2004-02-26 00:00:00-05:00  3.827965  3.837743  3.772558  3.810039  2266000   
2004-02-27 00:00:00-05:00  3.800265  3.956708  3.780709  3.951819  2272800   

                           Next Day Price  Target  
Date                                               
2004-02-23 00:00:00-05:00        3.852410       0  
2004-02-24 00:00:00-05:00        3.837746       0  
2004-02-25 00:00:00-05:00        3.810039       0  
2004-02-26 00:00:00-05:00        3.951819       1  
2004-02-27 00:00:00-05:00        4.122928       1

In [57]:
df.shape

(5034, 7)

In [60]:
train = df.iloc[:-200]
test = df.iloc[-200:]

X_train = train[['Close']]
y_train = train[['Target']]
X_test = test[['Close']]
y_test = test[['Target']]

In [61]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(4834, 1)
(200, 1)
(4834, 1)
(200, 1)


In [62]:
from sklearn.tree import DecisionTreeClassifier

DT = DecisionTreeClassifier()
D_Model = DT.fit(X_train,y_train)
DT_pred = DT.predict(X_test)
DT_pred

array([1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0])

In [63]:
report = classification_report(y_test, DT_pred)
print(report)

              precision    recall  f1-score   support

           0       0.46      0.51      0.48        90
           1       0.56      0.50      0.53       110

    accuracy                           0.51       200
   macro avg       0.51      0.51      0.50       200
weighted avg       0.51      0.51      0.51       200



In [64]:
from sklearn.ensemble import RandomForestClassifier

RF = RandomForestClassifier()
RF_Model = RF.fit(X_train,y_train)
RF_pred = RF.predict(X_test)
RF_pred

array([1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0])

In [65]:
report = classification_report(y_test, RF_pred)
print(report)

              precision    recall  f1-score   support

           0       0.46      0.51      0.48        90
           1       0.56      0.50      0.53       110

    accuracy                           0.51       200
   macro avg       0.51      0.51      0.50       200
weighted avg       0.51      0.51      0.51       200



In [45]:
from sklearn.model_selection import GridSearchCV, train_test_split
from sklearn.metrics import accuracy_score

In [17]:
rf_model = RandomForestClassifier()

param_grid = {
    'n_estimators':[20,60,80,100,150],
    'max_depth': [None, 5 ,10, 20],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

grid_search = GridSearchCV(estimator=rf_model, param_grid=param_grid, cv=3, scoring='accuracy', n_jobs=-1)
grid_search.fit(X_train, y_train)

# Get the best hyperparameters
best_params = grid_search.best_params_
print("Best Hyperparameters:", best_params)

# Use the best model to make predictions on the test data
best_model = grid_search.best_estimator_
predictions = best_model.predict(X_test)

# Evaluate the accuracy of the best model
accuracy = accuracy_score(y_test, predictions)
print(f"Accuracy of the Best Model: {accuracy}")

Best Hyperparameters: {'max_depth': 20, 'min_samples_leaf': 4, 'min_samples_split': 5, 'n_estimators': 20}
Accuracy of the Best Model: 0.42


In [66]:
RF = RandomForestClassifier(n_estimators = 20, min_samples_leaf = 4, min_samples_split = 5)
RF_Model = RF.fit(X_train,y_train)
RF_pred = RF.predict(X_test)
RF_pred

array([1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 1])

In [67]:
report = classification_report(y_test, RF_pred)
print(report)

              precision    recall  f1-score   support

           0       0.41      0.50      0.45        90
           1       0.51      0.42      0.46       110

    accuracy                           0.46       200
   macro avg       0.46      0.46      0.45       200
weighted avg       0.46      0.46      0.46       200



In [52]:
from sklearn.ensemble import AdaBoostClassifier

AB = AdaBoostClassifier()
AB_Model = RF.fit(X_train,y_train)
AB_pred = RF.predict(X_test)
AB_pred

array([0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [76]:
report = classification_report(y_test, AB_pred)
print(report)

              precision    recall  f1-score   support

           0       0.48      0.98      0.65        95
           1       0.75      0.06      0.11       105

    accuracy                           0.49       200
   macro avg       0.62      0.52      0.38       200
weighted avg       0.62      0.49      0.36       200



In [68]:
## PWR

In [70]:
Stock = yf.Ticker("PWR")
df = Stock.history(period = '20y')
df.head()

Open      High       Low     Close   Volume  \
Date                                                                         
2004-02-23 00:00:00-05:00  8.584274  8.633439  8.417112  8.456445   330200   
2004-02-24 00:00:00-05:00  8.358115  8.594109  8.190953  8.289284   537200   
2004-02-25 00:00:00-05:00  8.249949  8.466276  8.072954  8.466276   496400   
2004-02-26 00:00:00-05:00  8.466277  8.485944  7.709131  8.436778  2063400   
2004-02-27 00:00:00-05:00  8.318781  8.456445  8.269616  8.456445   804000   

                           Dividends  Stock Splits  
Date                                                
2004-02-23 00:00:00-05:00        0.0           0.0  
2004-02-24 00:00:00-05:00        0.0           0.0  
2004-02-25 00:00:00-05:00        0.0           0.0  
2004-02-26 00:00:00-05:00        0.0           0.0  
2004-02-27 00:00:00-05:00        0.0           0.0

In [71]:
df.drop(['Dividends', 'Stock Splits'], axis = 1, inplace = True)
df['Next Day Price'] = df['Close'].shift(-1)
df['Target'] = (df['Next Day Price'] > df['Close']).astype(int)
df.head()

Open      High       Low     Close   Volume  \
Date                                                                         
2004-02-23 00:00:00-05:00  8.584274  8.633439  8.417112  8.456445   330200   
2004-02-24 00:00:00-05:00  8.358115  8.594109  8.190953  8.289284   537200   
2004-02-25 00:00:00-05:00  8.249949  8.466276  8.072954  8.466276   496400   
2004-02-26 00:00:00-05:00  8.466277  8.485944  7.709131  8.436778  2063400   
2004-02-27 00:00:00-05:00  8.318781  8.456445  8.269616  8.456445   804000   

                           Next Day Price  Target  
Date                                               
2004-02-23 00:00:00-05:00        8.289284       0  
2004-02-24 00:00:00-05:00        8.466276       1  
2004-02-25 00:00:00-05:00        8.436778       0  
2004-02-26 00:00:00-05:00        8.456445       1  
2004-02-27 00:00:00-05:00        8.485943       1

In [72]:
train = df.iloc[:-200]
test = df.iloc[-200:]

X_train = train[['Close']]
y_train = train[['Target']]
X_test = test[['Close']]
y_test = test[['Target']]

In [73]:
from sklearn.tree import DecisionTreeClassifier

DT = DecisionTreeClassifier()
D_Model = DT.fit(X_train,y_train)
DT_pred = DT.predict(X_test)
DT_pred

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [74]:
report = classification_report(y_test, DT_pred)
print(report)

              precision    recall  f1-score   support

           0       0.48      0.98      0.64        95
           1       0.67      0.04      0.07       105

    accuracy                           0.48       200
   macro avg       0.57      0.51      0.36       200
weighted avg       0.58      0.48      0.34       200



In [77]:
from sklearn.ensemble import AdaBoostClassifier

AB = AdaBoostClassifier()
AB_Model = RF.fit(X_train,y_train)
AB_pred = RF.predict(X_test)
AB_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [78]:
report = classification_report(y_test, AB_pred)
print(report)

              precision    recall  f1-score   support

           0       0.48      0.98      0.65        95
           1       0.71      0.05      0.09       105

    accuracy                           0.49       200
   macro avg       0.60      0.51      0.37       200
weighted avg       0.60      0.49      0.35       200



# PANW

In [9]:
Stock = yf.Ticker("PANW")
df = Stock.history(period = '20y')
df.head()

Open       High        Low      Close  \
Date                                                                    
2012-07-20 00:00:00-04:00  18.383333  20.690001  17.700001  17.709999   
2012-07-23 00:00:00-04:00  17.533333  18.000000  17.033333  17.170000   
2012-07-24 00:00:00-04:00  17.333332  18.666668  17.173332  18.500000   
2012-07-25 00:00:00-04:00  18.833332  19.666668  18.433332  19.650000   
2012-07-26 00:00:00-04:00  19.926666  20.616667  19.360001  19.959999   

                             Volume  Dividends  Stock Splits  
Date                                                          
2012-07-20 00:00:00-04:00  21048300        0.0           0.0  
2012-07-23 00:00:00-04:00   2365200        0.0           0.0  
2012-07-24 00:00:00-04:00   2150400        0.0           0.0  
2012-07-25 00:00:00-04:00   1799100        0.0           0.0  
2012-07-26 00:00:00-04:00   1283400        0.0           0.0

In [10]:
df.drop(['Dividends', 'Stock Splits'], axis = 1, inplace = True)
df['Next Day Price'] = df['Close'].shift(-1)
df['Target'] = (df['Next Day Price'] > df['Close']).astype(int)
df.head()

Open       High        Low      Close  \
Date                                                                    
2012-07-20 00:00:00-04:00  18.383333  20.690001  17.700001  17.709999   
2012-07-23 00:00:00-04:00  17.533333  18.000000  17.033333  17.170000   
2012-07-24 00:00:00-04:00  17.333332  18.666668  17.173332  18.500000   
2012-07-25 00:00:00-04:00  18.833332  19.666668  18.433332  19.650000   
2012-07-26 00:00:00-04:00  19.926666  20.616667  19.360001  19.959999   

                             Volume  Next Day Price  Target  
Date                                                         
2012-07-20 00:00:00-04:00  21048300       17.170000       0  
2012-07-23 00:00:00-04:00   2365200       18.500000       1  
2012-07-24 00:00:00-04:00   2150400       19.650000       1  
2012-07-25 00:00:00-04:00   1799100       19.959999       1  
2012-07-26 00:00:00-04:00   1283400       19.000000       0

In [11]:
train = df.iloc[:-200]
test = df.iloc[-200:]

X_train = train[['Close']]
y_train = train[['Target']]
X_test = test[['Close']]
y_test = test[['Target']]

In [12]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(2715, 1)
(200, 1)
(2715, 1)
(200, 1)


In [13]:
from sklearn.tree import DecisionTreeClassifier

DT = DecisionTreeClassifier()
D_Model = DT.fit(X_train,y_train)
DT_pred = DT.predict(X_test)
DT_pred

array([0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [15]:
report = classification_report(y_test, DT_pred)
print(report)

              precision    recall  f1-score   support

           0       0.41      0.94      0.57        84
           1       0.38      0.03      0.05       116

    accuracy                           0.41       200
   macro avg       0.39      0.48      0.31       200
weighted avg       0.39      0.41      0.27       200



In [16]:
from sklearn.model_selection import GridSearchCV, train_test_split
from sklearn.metrics import accuracy_score

In [18]:
rf_model = RandomForestClassifier()

param_grid = {
    'n_estimators':[20,60,80,100,150],
    'max_depth': [None, 5 ,10, 20],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

grid_search = GridSearchCV(estimator=rf_model, param_grid=param_grid, cv=3, scoring='accuracy', n_jobs=-1)
grid_search.fit(X_train, y_train)

# Get the best hyperparameters
best_params = grid_search.best_params_
print("Best Hyperparameters:", best_params)

# Use the best model to make predictions on the test data
best_model = grid_search.best_estimator_
predictions = best_model.predict(X_test)

# Evaluate the accuracy of the best model
accuracy = accuracy_score(y_test, predictions)
print(f"Accuracy of the Best Model: {accuracy}")

Best Hyperparameters: {'max_depth': 5, 'min_samples_leaf': 2, 'min_samples_split': 10, 'n_estimators': 20}
Accuracy of the Best Model: 0.42


In [19]:
RF = RandomForestClassifier(n_estimators = 20, min_samples_leaf = 4, min_samples_split = 5)
RF_Model = RF.fit(X_train,y_train)
RF_pred = RF.predict(X_test)
RF_pred

array([0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [20]:
report = classification_report(y_test, RF_pred)
print(report)

              precision    recall  f1-score   support

           0       0.42      0.96      0.58        84
           1       0.50      0.03      0.05       116

    accuracy                           0.42       200
   macro avg       0.46      0.50      0.32       200
weighted avg       0.47      0.42      0.27       200



In [21]:
from sklearn.ensemble import AdaBoostClassifier

AB = AdaBoostClassifier()
AB_Model = RF.fit(X_train,y_train)
AB_pred = RF.predict(X_test)
AB_pred

array([1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [22]:
report = classification_report(y_test, AB_pred)
print(report)

              precision    recall  f1-score   support

           0       0.42      0.96      0.58        84
           1       0.57      0.03      0.07       116

    accuracy                           0.42       200
   macro avg       0.50      0.50      0.32       200
weighted avg       0.51      0.42      0.28       200



# TSLA

In [23]:
Stock = yf.Ticker("TSLA")
df = Stock.history(period = '20y')
df.head()

Open      High       Low     Close     Volume  \
Date                                                                           
2010-06-29 00:00:00-04:00  1.266667  1.666667  1.169333  1.592667  281494500   
2010-06-30 00:00:00-04:00  1.719333  2.028000  1.553333  1.588667  257806500   
2010-07-01 00:00:00-04:00  1.666667  1.728000  1.351333  1.464000  123282000   
2010-07-02 00:00:00-04:00  1.533333  1.540000  1.247333  1.280000   77097000   
2010-07-06 00:00:00-04:00  1.333333  1.333333  1.055333  1.074000  103003500   

                           Dividends  Stock Splits  
Date                                                
2010-06-29 00:00:00-04:00        0.0           0.0  
2010-06-30 00:00:00-04:00        0.0           0.0  
2010-07-01 00:00:00-04:00        0.0           0.0  
2010-07-02 00:00:00-04:00        0.0           0.0  
2010-07-06 00:00:00-04:00        0.0           0.0

In [24]:
df.drop(['Dividends', 'Stock Splits'], axis = 1, inplace = True)
df['Next Day Price'] = df['Close'].shift(-1)
df['Target'] = (df['Next Day Price'] > df['Close']).astype(int)
df.head()

Open      High       Low     Close     Volume  \
Date                                                                           
2010-06-29 00:00:00-04:00  1.266667  1.666667  1.169333  1.592667  281494500   
2010-06-30 00:00:00-04:00  1.719333  2.028000  1.553333  1.588667  257806500   
2010-07-01 00:00:00-04:00  1.666667  1.728000  1.351333  1.464000  123282000   
2010-07-02 00:00:00-04:00  1.533333  1.540000  1.247333  1.280000   77097000   
2010-07-06 00:00:00-04:00  1.333333  1.333333  1.055333  1.074000  103003500   

                           Next Day Price  Target  
Date                                               
2010-06-29 00:00:00-04:00        1.588667       0  
2010-06-30 00:00:00-04:00        1.464000       0  
2010-07-01 00:00:00-04:00        1.280000       0  
2010-07-02 00:00:00-04:00        1.074000       0  
2010-07-06 00:00:00-04:00        1.053333       0

In [25]:
train = df.iloc[:-200]
test = df.iloc[-200:]

X_train = train[['Close']]
y_train = train[['Target']]
X_test = test[['Close']]
y_test = test[['Target']]

In [26]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(3235, 1)
(200, 1)
(3235, 1)
(200, 1)


In [30]:
from sklearn.tree import DecisionTreeClassifier

DT = DecisionTreeClassifier()
D_Model = DT.fit(X_train,y_train)
DT_pred = DT.predict(X_test)
DT_pred

array([1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0])

In [31]:
report = classification_report(y_test, DT_pred)
print(report)

              precision    recall  f1-score   support

           0       0.49      0.39      0.43        95
           1       0.53      0.63      0.58       105

    accuracy                           0.52       200
   macro avg       0.51      0.51      0.50       200
weighted avg       0.51      0.52      0.51       200



In [32]:
from sklearn.model_selection import GridSearchCV, train_test_split
from sklearn.metrics import accuracy_score

In [33]:
rf_model = RandomForestClassifier()

param_grid = {
    'n_estimators':[20,60,80,100,150],
    'max_depth': [None, 5 ,10, 20],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

grid_search = GridSearchCV(estimator=rf_model, param_grid=param_grid, cv=3, scoring='accuracy', n_jobs=-1)
grid_search.fit(X_train, y_train)

# Get the best hyperparameters
best_params = grid_search.best_params_
print("Best Hyperparameters:", best_params)

# Use the best model to make predictions on the test data
best_model = grid_search.best_estimator_
predictions = best_model.predict(X_test)

# Evaluate the accuracy of the best model
accuracy = accuracy_score(y_test, predictions)
print(f"Accuracy of the Best Model: {accuracy}")

Best Hyperparameters: {'max_depth': 20, 'min_samples_leaf': 4, 'min_samples_split': 5, 'n_estimators': 20}
Accuracy of the Best Model: 0.505


In [34]:
RF = RandomForestClassifier(n_estimators = 20, min_samples_leaf = 4, min_samples_split = 5)
RF_Model = RF.fit(X_train,y_train)
RF_pred = RF.predict(X_test)
RF_pred

array([1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 0])

In [35]:
report = classification_report(y_test, RF_pred)
print(report)

              precision    recall  f1-score   support

           0       0.44      0.29      0.35        95
           1       0.51      0.66      0.57       105

    accuracy                           0.48       200
   macro avg       0.47      0.48      0.46       200
weighted avg       0.47      0.48      0.47       200



In [36]:
from sklearn.ensemble import AdaBoostClassifier

AB = AdaBoostClassifier()
AB_Model = RF.fit(X_train,y_train)
AB_pred = RF.predict(X_test)
AB_pred

array([1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 0])

In [37]:
report = classification_report(y_test, AB_pred)
print(report)

              precision    recall  f1-score   support

           0       0.41      0.32      0.36        95
           1       0.48      0.58      0.53       105

    accuracy                           0.46       200
   macro avg       0.44      0.45      0.44       200
weighted avg       0.45      0.46      0.45       200



# NVDA

In [38]:
Stock = yf.Ticker("NVDA")
df = Stock.history(period = '20y')
df.head()

Open      High       Low     Close    Volume  \
Date                                                                          
2004-02-23 00:00:00-05:00  1.842335  1.845393  1.756716  1.781179  85333200   
2004-02-24 00:00:00-05:00  1.750600  1.772770  1.690973  1.710085  70838400   
2004-02-25 00:00:00-05:00  1.720787  1.752894  1.701676  1.720023  65251200   
2004-02-26 00:00:00-05:00  1.745249  1.748307  1.710085  1.731489  34497600   
2004-02-27 00:00:00-05:00  1.735311  1.736840  1.674919  1.700911  59554800   

                           Dividends  Stock Splits  
Date                                                
2004-02-23 00:00:00-05:00        0.0           0.0  
2004-02-24 00:00:00-05:00        0.0           0.0  
2004-02-25 00:00:00-05:00        0.0           0.0  
2004-02-26 00:00:00-05:00        0.0           0.0  
2004-02-27 00:00:00-05:00        0.0           0.0

In [39]:
df.drop(['Dividends', 'Stock Splits'], axis = 1, inplace = True)
df['Next Day Price'] = df['Close'].shift(-1)
df['Target'] = (df['Next Day Price'] > df['Close']).astype(int)
df.head()

Open      High       Low     Close    Volume  \
Date                                                                          
2004-02-23 00:00:00-05:00  1.842335  1.845393  1.756716  1.781179  85333200   
2004-02-24 00:00:00-05:00  1.750600  1.772770  1.690973  1.710085  70838400   
2004-02-25 00:00:00-05:00  1.720787  1.752894  1.701676  1.720023  65251200   
2004-02-26 00:00:00-05:00  1.745249  1.748307  1.710085  1.731489  34497600   
2004-02-27 00:00:00-05:00  1.735311  1.736840  1.674919  1.700911  59554800   

                           Next Day Price  Target  
Date                                               
2004-02-23 00:00:00-05:00        1.710085       0  
2004-02-24 00:00:00-05:00        1.720023       1  
2004-02-25 00:00:00-05:00        1.731489       1  
2004-02-26 00:00:00-05:00        1.700911       0  
2004-02-27 00:00:00-05:00        1.726138       1

In [40]:
train = df.iloc[:-200]
test = df.iloc[-200:]

X_train = train[['Close']]
y_train = train[['Target']]
X_test = test[['Close']]
y_test = test[['Target']]

In [41]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(4834, 1)
(200, 1)
(4834, 1)
(200, 1)


In [42]:
from sklearn.tree import DecisionTreeClassifier

DT = DecisionTreeClassifier()
D_Model = DT.fit(X_train,y_train)
DT_pred = DT.predict(X_test)
DT_pred

array([0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [43]:
report = classification_report(y_test, DT_pred)
print(report)

              precision    recall  f1-score   support

           0       0.44      0.96      0.60        89
           1       0.20      0.01      0.02       111

    accuracy                           0.43       200
   macro avg       0.32      0.48      0.31       200
weighted avg       0.30      0.43      0.28       200



In [44]:
from sklearn.model_selection import GridSearchCV, train_test_split
from sklearn.metrics import accuracy_score

In [45]:
rf_model = RandomForestClassifier()

param_grid = {
    'n_estimators':[20,60,80,100,150],
    'max_depth': [None, 5 ,10, 20],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

grid_search = GridSearchCV(estimator=rf_model, param_grid=param_grid, cv=3, scoring='accuracy', n_jobs=-1)
grid_search.fit(X_train, y_train)

# Get the best hyperparameters
best_params = grid_search.best_params_
print("Best Hyperparameters:", best_params)

# Use the best model to make predictions on the test data
best_model = grid_search.best_estimator_
predictions = best_model.predict(X_test)

# Evaluate the accuracy of the best model
accuracy = accuracy_score(y_test, predictions)
print(f"Accuracy of the Best Model: {accuracy}")

Best Hyperparameters: {'max_depth': 20, 'min_samples_leaf': 4, 'min_samples_split': 5, 'n_estimators': 60}
Accuracy of the Best Model: 0.435


In [46]:
RF = RandomForestClassifier(n_estimators = 20, min_samples_leaf = 4, min_samples_split = 5)
RF_Model = RF.fit(X_train,y_train)
RF_pred = RF.predict(X_test)
RF_pred

array([0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [47]:
report = classification_report(y_test, RF_pred)
print(report)

              precision    recall  f1-score   support

           0       0.44      0.97      0.60        89
           1       0.25      0.01      0.02       111

    accuracy                           0.43       200
   macro avg       0.34      0.49      0.31       200
weighted avg       0.33      0.43      0.28       200



In [48]:
from sklearn.ensemble import AdaBoostClassifier

AB = AdaBoostClassifier()
AB_Model = RF.fit(X_train,y_train)
AB_pred = RF.predict(X_test)
AB_pred

array([0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [49]:
report = classification_report(y_test, AB_pred)
print(report)

              precision    recall  f1-score   support

           0       0.44      0.96      0.60        89
           1       0.33      0.02      0.03       111

    accuracy                           0.43       200
   macro avg       0.39      0.49      0.32       200
weighted avg       0.38      0.43      0.29       200



# AVGO

In [50]:
Stock = yf.Ticker("AVGO")
df = Stock.history(period = '20y')
df.head()

Open       High        Low      Close  \
Date                                                                    
2009-08-06 00:00:00-04:00  11.886165  12.181518  11.209014  11.655645   
2009-08-07 00:00:00-04:00  11.634035  12.073463  11.547591  11.835740   
2009-08-10 00:00:00-04:00  11.979812  11.979812  11.245031  11.504366   
2009-08-11 00:00:00-04:00  11.511574  11.525982  11.165795  11.288259   
2009-08-12 00:00:00-04:00  11.634038  11.670057  11.281055  11.525982   

                             Volume  Dividends  Stock Splits  
Date                                                          
2009-08-06 00:00:00-04:00  24197800        0.0           0.0  
2009-08-07 00:00:00-04:00   2454300        0.0           0.0  
2009-08-10 00:00:00-04:00   2421000        0.0           0.0  
2009-08-11 00:00:00-04:00   2305400        0.0           0.0  
2009-08-12 00:00:00-04:00   1451300        0.0           0.0

In [51]:
df.drop(['Dividends', 'Stock Splits'], axis = 1, inplace = True)
df['Next Day Price'] = df['Close'].shift(-1)
df['Target'] = (df['Next Day Price'] > df['Close']).astype(int)
df.head()

Open       High        Low      Close  \
Date                                                                    
2009-08-06 00:00:00-04:00  11.886165  12.181518  11.209014  11.655645   
2009-08-07 00:00:00-04:00  11.634035  12.073463  11.547591  11.835740   
2009-08-10 00:00:00-04:00  11.979812  11.979812  11.245031  11.504366   
2009-08-11 00:00:00-04:00  11.511574  11.525982  11.165795  11.288259   
2009-08-12 00:00:00-04:00  11.634038  11.670057  11.281055  11.525982   

                             Volume  Next Day Price  Target  
Date                                                         
2009-08-06 00:00:00-04:00  24197800       11.835740       1  
2009-08-07 00:00:00-04:00   2454300       11.504366       0  
2009-08-10 00:00:00-04:00   2421000       11.288259       0  
2009-08-11 00:00:00-04:00   2305400       11.525982       1  
2009-08-12 00:00:00-04:00   1451300       11.922184       1

In [52]:
train = df.iloc[:-200]
test = df.iloc[-200:]

X_train = train[['Close']]
y_train = train[['Target']]
X_test = test[['Close']]
y_test = test[['Target']]

In [53]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(3460, 1)
(200, 1)
(3460, 1)
(200, 1)


In [54]:
from sklearn.tree import DecisionTreeClassifier

DT = DecisionTreeClassifier()
D_Model = DT.fit(X_train,y_train)
DT_pred = DT.predict(X_test)
DT_pred

array([1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [55]:
report = classification_report(y_test, DT_pred)
print(report)

              precision    recall  f1-score   support

           0       0.46      0.99      0.63        91
           1       0.80      0.04      0.07       109

    accuracy                           0.47       200
   macro avg       0.63      0.51      0.35       200
weighted avg       0.65      0.47      0.32       200



In [56]:
from sklearn.model_selection import GridSearchCV, train_test_split
from sklearn.metrics import accuracy_score

In [57]:
rf_model = RandomForestClassifier()

param_grid = {
    'n_estimators':[20,60,80,100,150],
    'max_depth': [None, 5 ,10, 20],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

grid_search = GridSearchCV(estimator=rf_model, param_grid=param_grid, cv=3, scoring='accuracy', n_jobs=-1)
grid_search.fit(X_train, y_train)

# Get the best hyperparameters
best_params = grid_search.best_params_
print("Best Hyperparameters:", best_params)

# Use the best model to make predictions on the test data
best_model = grid_search.best_estimator_
predictions = best_model.predict(X_test)

# Evaluate the accuracy of the best model
accuracy = accuracy_score(y_test, predictions)
print(f"Accuracy of the Best Model: {accuracy}")

Best Hyperparameters: {'max_depth': None, 'min_samples_leaf': 1, 'min_samples_split': 5, 'n_estimators': 20}
Accuracy of the Best Model: 0.47


In [58]:
RF = RandomForestClassifier(n_estimators = 20, min_samples_leaf = 4, min_samples_split = 5)
RF_Model = RF.fit(X_train,y_train)
RF_pred = RF.predict(X_test)
RF_pred

array([1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [59]:
report = classification_report(y_test, RF_pred)
print(report)

              precision    recall  f1-score   support

           0       0.46      0.99      0.63        91
           1       0.80      0.04      0.07       109

    accuracy                           0.47       200
   macro avg       0.63      0.51      0.35       200
weighted avg       0.65      0.47      0.32       200



In [60]:
from sklearn.ensemble import AdaBoostClassifier

AB = AdaBoostClassifier()
AB_Model = RF.fit(X_train,y_train)
AB_pred = RF.predict(X_test)
AB_pred

array([1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [61]:
report = classification_report(y_test, AB_pred)
print(report)

              precision    recall  f1-score   support

           0       0.46      0.99      0.63        91
           1       0.80      0.04      0.07       109

    accuracy                           0.47       200
   macro avg       0.63      0.51      0.35       200
weighted avg       0.65      0.47      0.32       200



# ANET

In [62]:
Stock = yf.Ticker("ANET")
df = Stock.history(period = '20y')
df.head()

Open     High      Low   Close    Volume  \
Date                                                                     
2014-06-06 00:00:00-04:00  13.8125  15.0000  13.7500  13.750  29020400   
2014-06-09 00:00:00-04:00  14.0625  14.2500  13.7500  13.800   2867600   
2014-06-10 00:00:00-04:00  13.8125  15.0000  13.8125  15.000   3947200   
2014-06-11 00:00:00-04:00  15.0000  15.8750  14.6650  15.875   2642000   
2014-06-12 00:00:00-04:00  15.9125  16.9575  15.7675  16.500   2917200   

                           Dividends  Stock Splits  
Date                                                
2014-06-06 00:00:00-04:00        0.0           0.0  
2014-06-09 00:00:00-04:00        0.0           0.0  
2014-06-10 00:00:00-04:00        0.0           0.0  
2014-06-11 00:00:00-04:00        0.0           0.0  
2014-06-12 00:00:00-04:00        0.0           0.0

In [63]:
df.drop(['Dividends', 'Stock Splits'], axis = 1, inplace = True)
df['Next Day Price'] = df['Close'].shift(-1)
df['Target'] = (df['Next Day Price'] > df['Close']).astype(int)
df.head()

Open     High      Low   Close    Volume  \
Date                                                                     
2014-06-06 00:00:00-04:00  13.8125  15.0000  13.7500  13.750  29020400   
2014-06-09 00:00:00-04:00  14.0625  14.2500  13.7500  13.800   2867600   
2014-06-10 00:00:00-04:00  13.8125  15.0000  13.8125  15.000   3947200   
2014-06-11 00:00:00-04:00  15.0000  15.8750  14.6650  15.875   2642000   
2014-06-12 00:00:00-04:00  15.9125  16.9575  15.7675  16.500   2917200   

                           Next Day Price  Target  
Date                                               
2014-06-06 00:00:00-04:00          13.800       1  
2014-06-09 00:00:00-04:00          15.000       1  
2014-06-10 00:00:00-04:00          15.875       1  
2014-06-11 00:00:00-04:00          16.500       1  
2014-06-12 00:00:00-04:00          17.395       1

In [64]:
train = df.iloc[:-200]
test = df.iloc[-200:]

X_train = train[['Close']]
y_train = train[['Target']]
X_test = test[['Close']]
y_test = test[['Target']]

In [65]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(2244, 1)
(200, 1)
(2244, 1)
(200, 1)


In [66]:
from sklearn.tree import DecisionTreeClassifier

DT = DecisionTreeClassifier()
D_Model = DT.fit(X_train,y_train)
DT_pred = DT.predict(X_test)
DT_pred

array([1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [67]:
report = classification_report(y_test, DT_pred)
print(report)

              precision    recall  f1-score   support

           0       0.42      0.84      0.56        86
           1       0.53      0.14      0.22       114

    accuracy                           0.44       200
   macro avg       0.48      0.49      0.39       200
weighted avg       0.49      0.44      0.37       200



In [68]:
from sklearn.model_selection import GridSearchCV, train_test_split
from sklearn.metrics import accuracy_score

In [69]:
rf_model = RandomForestClassifier()

param_grid = {
    'n_estimators':[20,60,80,100,150],
    'max_depth': [None, 5 ,10, 20],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

grid_search = GridSearchCV(estimator=rf_model, param_grid=param_grid, cv=3, scoring='accuracy', n_jobs=-1)
grid_search.fit(X_train, y_train)

# Get the best hyperparameters
best_params = grid_search.best_params_
print("Best Hyperparameters:", best_params)

# Use the best model to make predictions on the test data
best_model = grid_search.best_estimator_
predictions = best_model.predict(X_test)

# Evaluate the accuracy of the best model
accuracy = accuracy_score(y_test, predictions)
print(f"Accuracy of the Best Model: {accuracy}")

Best Hyperparameters: {'max_depth': 5, 'min_samples_leaf': 1, 'min_samples_split': 5, 'n_estimators': 150}
Accuracy of the Best Model: 0.455


In [70]:
RF = RandomForestClassifier(n_estimators = 20, min_samples_leaf = 4, min_samples_split = 5)
RF_Model = RF.fit(X_train,y_train)
RF_pred = RF.predict(X_test)
RF_pred

array([1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [71]:
report = classification_report(y_test, RF_pred)
print(report)

              precision    recall  f1-score   support

           0       0.43      0.86      0.57        86
           1       0.57      0.14      0.23       114

    accuracy                           0.45       200
   macro avg       0.50      0.50      0.40       200
weighted avg       0.51      0.45      0.38       200



In [72]:
from sklearn.ensemble import AdaBoostClassifier

AB = AdaBoostClassifier()
AB_Model = RF.fit(X_train,y_train)
AB_pred = RF.predict(X_test)
AB_pred

array([1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [ ]:
report = classification_report(y_test, AB_pred)
print(report)